apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: guestbook
  namespace: guestbook
spec:
  host: guestbook.yzw-test-5ecb78232f6f5cc392e551f4ec27be9c-0000.us-south.containers.appdomain.cloud
  port:
    targetPort: 80
  to:
    kind: Service
    name: frontend
    weight: 100
