kind: Service
apiVersion: v1
metadata:
  name: nginx-demo
  namespace: default
  labels:
    app: nginx-demo
spec:
  selector:
    app: nginx-demo
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
